// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_J38ArpNMy",
    "aws_user_pools_web_client_id": "7hov5di2hqup79i280f3699l64",
    "aws_appsync_graphqlEndpoint": "https://ianic67phvavhgp6mjbcyux7ru.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;